
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Peñate
 */
public class ventana3 extends javax.swing.JFrame {

    int pos=0;
    double vector[]= new double[10];
    public ventana3() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLadoCuadrado = new javax.swing.JTextField();
        btnAreaDiagonal = new javax.swing.JButton();
        txtLadoCirculo = new javax.swing.JTextField();
        txtRadioEsfera = new javax.swing.JTextField();
        txtDiagonoCubo = new javax.swing.JTextField();
        btnArea = new javax.swing.JButton();
        btnVol1 = new javax.swing.JButton();
        btnVol = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        txtIngresarDiez = new javax.swing.JTextField();
        btnCalculo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ventana3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Proporcione un lado del cuadrado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Proporcione el lado del circulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Proporcione el radio de la esfera");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Proporcione la diagonal de un cubo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Ingresar 10 letras");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtLadoCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadoCuadradoActionPerformed(evt);
            }
        });
        txtLadoCuadrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLadoCuadradoKeyTyped(evt);
            }
        });
        getContentPane().add(txtLadoCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 97, -1));

        btnAreaDiagonal.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnAreaDiagonal.setText("Calcular area y diagonal");
        btnAreaDiagonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaDiagonalActionPerformed(evt);
            }
        });
        getContentPane().add(btnAreaDiagonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        txtLadoCirculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLadoCirculoKeyTyped(evt);
            }
        });
        getContentPane().add(txtLadoCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 97, -1));

        txtRadioEsfera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRadioEsferaKeyTyped(evt);
            }
        });
        getContentPane().add(txtRadioEsfera, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 97, -1));

        txtDiagonoCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagonoCuboActionPerformed(evt);
            }
        });
        txtDiagonoCubo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiagonoCuboKeyTyped(evt);
            }
        });
        getContentPane().add(txtDiagonoCubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 97, -1));

        btnArea.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnArea.setText("Calcular area");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });
        getContentPane().add(btnArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        btnVol1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnVol1.setText("Calcular volumen");
        btnVol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVol1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        btnVol.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnVol.setText("Calcular volumen");
        btnVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolActionPerformed(evt);
            }
        });
        getContentPane().add(btnVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        btnIngresar.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnIngresar.setText(" Ingresar ");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane2.setViewportView(txtResultado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 240, -1));

        txtIngresarDiez.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresarDiezKeyTyped(evt);
            }
        });
        getContentPane().add(txtIngresarDiez, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 100, -1));

        btnCalculo.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnCalculo.setText("Calcular");
        btnCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 120, -1));

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton2.setText("Menú principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo (1).jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLadoCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadoCuadradoActionPerformed

    }//GEN-LAST:event_txtLadoCuadradoActionPerformed

    
    private void btnAreaDiagonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaDiagonalActionPerformed
       
        if(!txtLadoCuadrado.getText().isEmpty()){
        double numero = Double.parseDouble(this.txtLadoCuadrado.getText());
        double Area= ((numero)*(numero));
        double Diagonal= (Math.sqrt(numero*numero*2));
        txtResultado.setText("Area:"+Area+ "\nDiagonal:"+Diagonal);
        txtLadoCuadrado.setText("");
     }
        else{
            JOptionPane.showMessageDialog(null, "error");
            txtLadoCuadrado.requestFocus();
        }
    }//GEN-LAST:event_btnAreaDiagonalActionPerformed

    private void txtLadoCuadradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLadoCuadradoKeyTyped
        char c=evt.getKeyChar();
         if(Character.isLetter(c)){
           evt.consume();
        }
    }//GEN-LAST:event_txtLadoCuadradoKeyTyped

    private void txtLadoCirculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLadoCirculoKeyTyped
         char c=evt.getKeyChar();
         if(Character.isLetter(c)){
           evt.consume();
        }
    }//GEN-LAST:event_txtLadoCirculoKeyTyped

    private void txtRadioEsferaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRadioEsferaKeyTyped
       char c=evt.getKeyChar();
         if(Character.isLetter(c)){
           evt.consume();
        }
    }//GEN-LAST:event_txtRadioEsferaKeyTyped

    private void txtDiagonoCuboKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiagonoCuboKeyTyped
         char c=evt.getKeyChar();
         if(Character.isLetter(c)){
           evt.consume();
        }
    }//GEN-LAST:event_txtDiagonoCuboKeyTyped

    private void btnVol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVol1ActionPerformed
        if(!txtRadioEsfera.getText().isEmpty()){
        double numero= Double.parseDouble(txtRadioEsfera.getText());
         double volumen=(4*3.1416/3)*(numero*numero*numero);
         txtResultado.setText("Volumen:"+volumen);
          txtRadioEsfera.setText("");
        }
        else{
           JOptionPane.showMessageDialog(null, "error");
            txtRadioEsfera.requestFocus();
        }
    }//GEN-LAST:event_btnVol1ActionPerformed

    private void txtDiagonoCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagonoCuboActionPerformed
        
    }//GEN-LAST:event_txtDiagonoCuboActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       if(!txtIngresarDiez.getText().isEmpty()){
           double dato=Double.parseDouble(txtIngresarDiez.getText());
           vector[pos]=dato;
           txtIngresarDiez.setText("");         
           pos=pos+1;
           if(pos==10){
               txtIngresarDiez.setEnabled(false);              
           }   
           else{
             txtIngresarDiez.requestFocus();  
           }
       }         
       else{
           JOptionPane.showMessageDialog(null, "campo vacio");
           txtIngresarDiez.requestFocus();
       }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        if(!txtLadoCirculo.getText().isEmpty()){
        double num= Double.parseDouble(txtLadoCirculo.getText());
        double Area=(num*num)*(3.1416);
        txtResultado.setText("Volumen:"+Area);
        txtLadoCirculo.setText("");
        }
         else{
           JOptionPane.showMessageDialog(null, "error");
            txtLadoCirculo.requestFocus();
        }
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolActionPerformed
        if(!txtDiagonoCubo.getText().isEmpty()){
        double numero= Double.parseDouble(txtDiagonoCubo.getText());
        double volumen=(((Math.sqrt(2))/2)*numero)*(((Math.sqrt(2))/2)*numero)*(((Math.sqrt(2))/2)*numero);
        txtResultado.setText("Volumen:"+volumen);
         txtDiagonoCubo.setText("");
        }
        else{
           JOptionPane.showMessageDialog(null, "error");
            txtDiagonoCubo.requestFocus();
        }
    }//GEN-LAST:event_btnVolActionPerformed

    private void txtIngresarDiezKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresarDiezKeyTyped
        char c=evt.getKeyChar();
        int num=(int)evt.getKeyChar();
        if(Character.isLetter(c) && num>=32 || num<=47 ){
            evt.consume();
        }
        else{
            
        }       
    }//GEN-LAST:event_txtIngresarDiezKeyTyped

    private void btnCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoActionPerformed
       double sum=0,nume;
       double prom;
        if(pos==10){
            for(pos=0;pos<10;pos++){
                nume=vector[pos];
                sum=sum+nume;
                prom=sum/10;
                txtResultado.setText("Promedio: "+prom);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "ingrese todos los datos");
        }   
    }//GEN-LAST:event_btnCalculoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ventana2 obj= new ventana2();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnAreaDiagonal;
    private javax.swing.JButton btnCalculo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnVol;
    private javax.swing.JButton btnVol1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtDiagonoCubo;
    private javax.swing.JTextField txtIngresarDiez;
    private javax.swing.JTextField txtLadoCirculo;
    private javax.swing.JTextField txtLadoCuadrado;
    private javax.swing.JTextField txtRadioEsfera;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
