
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author use
 */
public class ventana5 extends javax.swing.JFrame {
            String marca,op;
    public ventana5() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        txtPpal.setEnabled(false);
        txtSecundario.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCPU = new javax.swing.JTextField();
        txtTamaño = new javax.swing.JTextField();
        txtRAM = new javax.swing.JTextField();
        txtGarantia = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cbxCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnPpal = new javax.swing.JRadioButton();
        btnSecundario = new javax.swing.JRadioButton();
        btnFlash = new javax.swing.JRadioButton();
        btnEjecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtPpal = new javax.swing.JTextField();
        txtSecundario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ventana5");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Puntajes de moviles");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("CPU numero de nucleos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Tamaño de Pantalla");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Cantidad de RAM");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Tiempo de Garantia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Precio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Marca");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtCPU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPUKeyTyped(evt);
            }
        });
        getContentPane().add(txtCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 90, -1));

        txtTamaño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamañoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 90, -1));

        txtRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRAMActionPerformed(evt);
            }
        });
        txtRAM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRAMKeyTyped(evt);
            }
        });
        getContentPane().add(txtRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 90, -1));

        txtGarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGarantiaKeyTyped(evt);
            }
        });
        getContentPane().add(txtGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, -1));

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 90, -1));

        cbxCombo.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        cbxCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEXUS", "PIXIE", "LENOVO", "HUAWEY", "SONY", "APPLE", "SAMSUNG", "ALCATEL", "LG", "OTRA", " " }));
        cbxCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxComboActionPerformed(evt);
            }
        });
        getContentPane().add(cbxCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Camaras");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btnPpal.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnPpal.setText("Principal");
        btnPpal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPpalActionPerformed(evt);
            }
        });
        getContentPane().add(btnPpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        btnSecundario.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnSecundario.setText("Secundaria");
        btnSecundario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecundarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        btnFlash.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnFlash.setText("Flash");
        btnFlash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlashActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlash, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        btnEjecutar.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 396, 450, 110));

        txtPpal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPpalKeyTyped(evt);
            }
        });
        getContentPane().add(txtPpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 60, -1));

        txtSecundario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSecundarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 70, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 100, -1));

        jButton2.setText("Menú principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/43136056-abstract-vector-future-technology-data-background-illustration-Stock-Photo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRAMActionPerformed
       
    }//GEN-LAST:event_txtRAMActionPerformed

    private void btnPpalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPpalActionPerformed
        txtPpal.setEnabled(true);
    }//GEN-LAST:event_btnPpalActionPerformed

    private void btnSecundarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecundarioActionPerformed
       txtSecundario.setEnabled(true);
    }//GEN-LAST:event_btnSecundarioActionPerformed

    private void txtCPUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPUKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
        }
        else{
           int cantidad=2;
           if(txtCPU.getText().length()>=cantidad){
               evt.consume();
               JOptionPane.showMessageDialog(null, "ingrese solo 2 digitos");
           }
        }
    }//GEN-LAST:event_txtCPUKeyTyped

    private void txtTamañoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamañoKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
        }
        else{
           int cantidad=3;
           if(txtTamaño.getText().length()>=cantidad){
               evt.consume();
               JOptionPane.showMessageDialog(null, "ingrese solo 3 digitos");
           }
        }
    }//GEN-LAST:event_txtTamañoKeyTyped

    private void txtRAMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRAMKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
        }
        else{
           int cantidad=3;
           if(txtRAM.getText().length()>=cantidad){
               evt.consume();
               JOptionPane.showMessageDialog(null, "ingrese solo 3 digitos");
           }
        }
    }//GEN-LAST:event_txtRAMKeyTyped

    private void txtGarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGarantiaKeyTyped
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
        }
        else{
           int cantidad=2;
           if(txtGarantia.getText().length()>=cantidad){
               evt.consume();
               JOptionPane.showMessageDialog(null, "ingrese solo 2 digitos");
           }
        }
    }//GEN-LAST:event_txtGarantiaKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
        }
        else{
           int cantidad=6;
           if(txtPrecio.getText().length()>=cantidad){
               evt.consume();
               JOptionPane.showMessageDialog(null, "ingrese solo 6 digitos");
           }
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        if(!txtCPU.getText().isEmpty() && !txtTamaño.getText().isEmpty() && !txtRAM.getText().isEmpty() && !txtGarantia.getText().isEmpty()
                && !txtPrecio.getText().isEmpty()){
        String cadena;
        cadena="El numero de CPU es:"+txtCPU.getText()+"\t\tEl tamaño de pantalla es:"+txtTamaño.getText()+"\n"
                + "La memoria es de:"+txtRAM.getText()+"\t\tLa garantia es de:"+txtGarantia.getText()+"\n"
                + "Su precio es de:"+txtPrecio.getText()+"\t\tLa marca es de:"+marca+"\n"
                + "Posee camara principal de:"+txtPpal.getText()+" Mpx, "+op+"\n"
                + "Posee camara secundaria de:"+txtSecundario.getText()+" Mpx, "+op;
        txtArea.setText(cadena);
        }
        else{
            JOptionPane.showMessageDialog(null, "Existen Campos Vacios");
        }
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void txtPpalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPpalKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){ 
            evt.consume();
        }
        else{
           int cantidad=4;
           if(txtPpal.getText().length()>=cantidad){
               evt.consume();
               JOptionPane.showMessageDialog(null, "ingrese solo 4 digitos");
           }
        }
    }//GEN-LAST:event_txtPpalKeyTyped

    private void txtSecundarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSecundarioKeyTyped
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
        }
        else{
           int cantidad=4;
           if(txtSecundario.getText().length()>=cantidad){
               evt.consume();
               JOptionPane.showMessageDialog(null, "ingrese solo 4 digitos");
           }
        }
    }//GEN-LAST:event_txtSecundarioKeyTyped

    private void cbxComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxComboActionPerformed
        int op=cbxCombo.getSelectedIndex();
        if(op==0){
            marca="NEXUS";
        }
        else if(op==1){
            marca="PIXIE";
        }
        else if(op==2){
            marca="LENOVO";
        }
        else if(op==3){
            marca="HUAWEY";
        }
        else if(op==4){
            marca="SONY";
        }
        else if(op==5){
            marca="APPLE";
        }
        else if(op==6){
            marca="SAMSUNG";
        }
        else if(op==7){
            marca="ALCATEL";
        }
        else if(op==8){
            marca="LG";
        }
        else if(op==9){
            marca="OTRA";
        }
    }//GEN-LAST:event_cbxComboActionPerformed

    private void btnFlashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlashActionPerformed
        if(btnFlash.isSelected()){
            op="Con Flash";
        }
    }//GEN-LAST:event_btnFlashActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ventana2 obj= new ventana2();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JRadioButton btnFlash;
    private javax.swing.JRadioButton btnPpal;
    private javax.swing.JRadioButton btnSecundario;
    private javax.swing.JComboBox<String> cbxCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtCPU;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtPpal;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRAM;
    private javax.swing.JTextField txtSecundario;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
}
